services:
  backend:
    image: docker.io/library/node:latest
    volumes:
      - ./backend:/app
    command: >
      sh -c "cd /app &&
             npm install &&
             npm start"
    ports:
      - 2999:2999
  frontend:
    image: docker.io/library/node:latest
    volumes:
      - ./frontend:/app
    command: >
      sh -c "cd /app &&
             npm install &&
             npm start"
    ports:
      - 3000:3000
  db:
    image: docker.io/library/mongo:latest
    ports:
      - 27017:27017